### ISSUE TITLE
When authentication token is changed, WebClient dies

### ISSUE THREAD

**Issue by hydrostaticcog** [FerrisChat/WebClient#10]
When I change my auth token while the WebClient is open, and I reload it, the webclient starts to die, tons of errors in the console.

**Comment by jay3332** [comment]
It should fall back to login screen, this fallback feature has been implemented weeks ago(?)

**Comment by hydrostaticcog** [comment]
Well it does not do that. It gets stuck on the loading screen.

**Comment by jay3332** [comment]
See https://github.com/FerrisChat/WebClient/blob/82f7d61b2ec5d0eb530c4e740f09f4bb5ceb1a0f/src/js/api/requests/RESTClient.ts#L104-L108

**Comment by jay3332** [comment]
oh nvm it's only 401

**Comment by jay3332** [comment]
Well this is to be fixed in the rewrite version of the WebClient

**Comment by jay3332** [comment]
Although not fixed in the backend, the WebClient rewrite now takes into account this bug and will fallback to the login page if this occurs.
